# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
allowed_ssh_cidr_blocks = ["10.1.0.0/16"]
private_subnets         = ["10.1.3.0/24", "10.1.4.0/24"]
public_subnets          = ["10.1.1.0/24", "10.1.2.0/24"]
vpc_cidr_block          = "10.1.0.0/16"
